module.exports = [
  require('./cache/ActiveGameplayModifier.json'),
  require('./cache/BroadcastRemoteClientInfo_ClientRemotePlayerHitMarkers.json'),
  require('./cache/BroadcastRemoteClientInfo_MapMarker.json'),
  require('./cache/BroadcastRemoteClientInfoCache.json'),
  require('./cache/InventoryCache.json'),
  require('./cache/GameplayCues.json'),
  require('./cache/GameStateCache.json'),
  require('./cache/PlayerPawn_NetMulticast_Athena_BatchedDamageCues.json'),
  require('./cache/PlayerPawnCache.json'),

  require('./properties/Containers.json'),
  require('./properties/BroadcastRemoteClientInfo.json'),
  require('./properties/BroadcastSpectatorInfo.json'),
  require('./properties/Inventory.json'),
  require('./properties/Pickup.json'),
  require('./properties/PlayerState.json'),
  require('./properties/GameState.json'),
  require('./properties/LabradorLlama.json'),
  require('./properties/PlayerBuilds.json'),
  require('./properties/PlayerPawn.json'),
  require('./properties/SafeZoneIndicator.json'),
  require('./properties/SoccerGame.json'),
  require('./properties/SpeedSign.json'),
  require('./properties/SupplyDrop.json'),
  require('./properties/Llama.json'),
  require('./properties/Vehicles.json'),

  require('./properties/components/HealthSet.json'),
  require('./properties/components/VehicleSeatComponent.json'),
];
