class PlayerMovement {
  ReplicatedMovement = ''
  ReplicatedWorldTimeSeconds = ''
  LastUpdateTime = ''
  bIsCrouched = false
  bIsSprinting = false
  bIsJumping = false
  bIsSlopeSliding = false
  bIsZiplining = false
  bIsTargeting = false
  bIsDBNO = false
  bIsHonking = false
  bIsInAnyStorm = false
  bIsWaitingForEmoteInteraction = false
  bIsPlayingEmote = false
  bIsSkydiving = false
  bIsSkydivingFromLaunchPad = false
  bIsSkydivingFromBus = false
  bIsParachuteOpen = false
  bIsParachuteForcedOpen = false
  bIsInWaterVolume = false
}
