class Player {
  Id = '';
  EpicId = '';
  BotId = '';
  IsBot = '';
  PlayerNameCustomOverride = '';
  IsGameSessionOwner = '';
  PlayerNumber = '';
  PlayerName = '';
  StreamerModeName = '';
  IsPartyLeader = '';
  TeamIndex = '';
  Level = '';
  SeasonLevelUIDisplay = '';
  PlatformUniqueNetId = '';
  HasFinishedLoading = '';
  HasStartedPlaying = '';
  IsUsingAnonymousMode = '';
  IsUsingStreamerMode = '';
  InventoryId = '';
  HasThankedBusDriver = '';
  Disconnected = '';
  RebootCounter = '';
  Placement = '';
  Kills = '';
  TeamKills = '';
  DeathCause = '';
  DeathCircumstance = '';
  DeathTags = '';
  DeathLocation = '';
  DeathTime = '';
  Cosmetics = '';
  CurrentWeapon = '';
  Locations = '';
}

module.exports = Player;
